### ISSUE TITLE
將暫存類檔案加入 .gitignore, 版本控制不需要紀錄暫存的檔案

### ISSUE THREAD

**Issue by yusheng0502** [WillyboyMoMo/HelloWorld#4]
```jsx
#Ignore thumbnails created by Windows
Thumbs.db
#Ignore files built by Visual Studio
*.obj
*.exe
*.pdb
*.user
*.aps
*.pch
*.vspscc
*_i.c
*_p.c
*.ncb
*.suo
*.tlb
*.tlh
*.bak
*.cache
*.ilk
*.log
[Bb]in
[Dd]ebug*/
*.lib
*.sbr
obj/
[Rr]elease*/
_ReSharper*/
[Tt]est[Rr]esult*
.vs/
#Nuget packages folder
packages/
```

**Comment by yusheng0502** [comment]
由於在加入.gitignore之前你已經有把暫存類的檔案做版本記錄(commit)了，因此目前的Repo中仍然會先前已經紀錄的暫存檔，請試著將這些檔案從 Git Repo中移除。
若成功移除，重新clone專案應該不會再出現這些檔案。

**Comment by WillyboyMoMo** [comment]
我這邊多次測試後，那些檔案應該已經沒有在裡面了唷。也有用另一台電腦做測試，也是很乾淨的。附圖為用終端機測試的結果以及我此專案的github頁面，再麻煩幫我看一下。
![螢幕擷取畫面 2024-11-01 223543](https://github.com/user-attachments/assets/1603adc5-7c2b-40ac-8042-1b5b25b0525e)
![螢幕擷取畫面 2024-11-01 223602](https://github.com/user-attachments/assets/48c4cffb-2f4f-4d72-8e66-13b2bb173665)

**Comment by WillyboyMoMo** [comment]
我重新在調整了
已經有成功移除了
再麻煩幫我看看
謝謝

**Comment by yusheng0502** [comment]
1. .gitignore 檔案沒有成功加入
2. 重新 clone 專案依然會包含期望排除的檔案

**Comment by WillyboyMoMo** [comment]
有將.gitignore 重新加入並放入根目錄
可以再幫我看看嗎?

或是您可以截圖給我看看是哪邊還有未忽略的檔案嗎?
謝謝
